# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1_a', models.ImageField(blank=True, upload_to='')),
                ('img_1_b', models.ImageField(blank=True, upload_to='')),
                ('img_two_a', models.ImageField(blank=True, upload_to='')),
                ('img_two_b', models.ImageField(blank=True, upload_to='')),
                ('img_3_a', models.ImageField(blank=True, upload_to='')),
                ('img_3_b', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
