# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171111_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_two_a',
            new_name='img_2_a',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_two_b',
        ),
        migrations.AddField(
            model_name='image',
            name='img_2_b',
            field=models.URLField(blank=True),
        ),
    ]
